import { GarageLevels } from "./interface.ts";
import { Images } from "../assets/images/images";




export const garageLevelList: GarageLevels[] = [
  {
    GarageLevelKey: 1,
    garageLevel: [
      {
        number: 1,
        xp: "0",
        img: Images.BMWZ4,
        img2: Images.ChevroletCamaroLT,
        img3: "",
        img4: "",
        name: "BMW Z4 LCI E89",
        name2: "Chevrolet Camaro LT",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 2,
    garageLevel: [
      {
        number: 2,
        xp: "4,000",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 3,
    garageLevel: [
      {
        number: 3,
        xp: "8,000",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 4,
    garageLevel: [
      {
        number: 4,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 5,
    garageLevel: [
      {
        number: 5,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 6,
    garageLevel: [
      {
        number: 6,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 7,
    garageLevel: [
      {
        number: 7,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 8,
    garageLevel: [
      {
        number: 8,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 9,
    garageLevel: [
      {
        number: 9,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 10,
    garageLevel: [
      {
        number: 10,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 11,
    garageLevel: [
      {
        number: 11,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 12,
    garageLevel: [
      {
        number: 12,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 13,
    garageLevel: [
      {
        number: 13,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 14,
    garageLevel: [
      {
        number: 14,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 15,
    garageLevel: [
      {
        number: 15,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 16,
    garageLevel: [
      {
        number: 16,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 17,
    garageLevel: [
      {
        number: 17,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 18,
    garageLevel: [
      {
        number: 18,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 19,
    garageLevel: [
      {
        number: 19,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 20,
    garageLevel: [
      {
        number: 20,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 21,
    garageLevel: [
      {
        number: 21,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 22,
    garageLevel: [
      {
        number: 22,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 23,
    garageLevel: [
      {
        number: 23,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 24,
    garageLevel: [
      {
        number: 24,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 25,
    garageLevel: [
      {
        number: 25,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 26,
    garageLevel: [
      {
        number: 26,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 27,
    garageLevel: [
      {
        number: 27,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 28,
    garageLevel: [
      {
        number: 28,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 29,
    garageLevel: [
      {
        number: 29,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 30,
    garageLevel: [
      {
        number: 30,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 31,
    garageLevel: [
      {
        number: 31,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 32,
    garageLevel: [
      {
        number: 32,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 33,
    garageLevel: [
      {
        number: 33,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 34,
    garageLevel: [
      {
        number: 34,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 35,
    garageLevel: [
      {
        number: 35,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 36,
    garageLevel: [
      {
        number: 36,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 37,
    garageLevel: [
      {
        number: 37,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 38,
    garageLevel: [
      {
        number: 38,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 39,
    garageLevel: [
      {
        number: 39,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 40,
    garageLevel: [
      {
        number: 40,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 41,
    garageLevel: [
      {
        number: 41,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 42,
    garageLevel: [
      {
        number: 42,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 43,
    garageLevel: [
      {
        number: 43,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 44,
    garageLevel: [
      {
        number: 44,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 45,
    garageLevel: [
      {
        number: 45,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 46,
    garageLevel: [
      {
        number: 46,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 47,
    garageLevel: [
      {
        number: 47,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 48,
    garageLevel: [
      {
        number: 48,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 49,
    garageLevel: [
      {
        number: 49,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 50,
    garageLevel: [
      {
        number: 50,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 51,
    garageLevel: [
      {
        number: 51,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 52,
    garageLevel: [
      {
        number: 52,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 53,
    garageLevel: [
      {
        number: 53,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 54,
    garageLevel: [
      {
        number: 54,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 55,
    garageLevel: [
      {
        number: 55,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 56,
    garageLevel: [
      {
        number: 56,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 57,
    garageLevel: [
      {
        number: 57,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 58,
    garageLevel: [
      {
        number: 58,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 59,
    garageLevel: [
      {
        number: 59,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
  {
    GarageLevelKey: 60,
    garageLevel: [
      {
        number: 60,
        xp: "0",
        img: "",
        img2: "",
        img3: "",
        img4: "",
        name: "",
        name2: "",
        name3: "",
        name4: "",
      },
    ],
  },
];
